
name: Build my application

on: [push]

jobs:
  build:
   
    name: Build the app
    runs-on: ubuntu-latest
    steps:
     # - name: Hello world
      #  uses: actions/hello-world-javascript-action@v1
      #  with:
       #   who-to-greet: 'Mona the Octocat'
       # id: hello
      # This step prints an output (time) from the previous step's action.
      - name: print current directory
        run: pwd
      - name: List fields in the directory
        run: ls
